CREATE TABLE IF NOT EXISTS Users (
    UserId INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    email   VARCHAR(50) NOT NULL UNIQUE,
    username    VARCHAR(50) NOT NULL UNIQUE,
    password    VARCHAR(100)
) ENGINE = InnoDB;